### ISSUE TITLE
请问项目接受PR吗？

### ISSUE THREAD

**Issue by PmcFizz** [hellowuxin/vue3-mindmap#22]
请问项目接受PR吗？
最近我也想到要做这样一个项目，但一搜，结果被你抢先做了。hahah。。。。兄弟，项目还缺人吗？

**Comment by hellowuxin** [comment]
目前这个项目基本上都没在维护了，忙于工作了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hellowuxin/vue3-mindmap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 晚上10:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hellowuxin/vue3-mindmap] 请问项目接受PR吗？ (#22)





 
请问项目接受PR吗？
 最近我也想到要做这样一个项目，但一搜，结果被你抢先做了。hahah。。。。兄弟，项目还缺人吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PmcFizz** [comment]
也是毕竟要挣钱养家。就是业余玩玩。如果和绩效有关，可能还会多花点时间搞搞。
